//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_color { get; set; }
        public decimal product_price { get; set; }
        public int category_id { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
